#[macro_use]
mod macros;

magic! {
    HEADER = "CRAMBLY GENERATED CRAM TEST";
    PATH_PREFIX = "ORIGINAL SOURCE: ";
    NAME_PREFIX = "START TEST CASE: ";
    COMMAND_PREFIX = "  $ ";
    COMMAND_CONT_PREFIX = "  > ";
    METADATA_HEADER = "CRAMBLY TEST CASE METADATA";
    OUTPUT_PREFIX = "  ";
    METADATA_COMMAND_END_LINE_PREFIX = "COMMAND END LINE: ";
    METADATA_OUTPUT_START_PREFIX = "OUTPUT START LINE: ";
    METADATA_OUTPUT_END_PREFIX = "OUTPUT END LINE: ";
    METADATA_LAST_PREFIX = "LAST: ";
    END_TEST_CASE = "END TEST CASE: ";
}
